apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "fabric-operator.fullname" . }}-psp
  labels:
    {{- include "fabric-operator.labels" . | nindent 4 }}
spec:
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: true
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
    - ALL
  allowedCapabilities:
    - NET_BIND_SERVICE
    - CHOWN
    - DAC_OVERRIDE
    - SETGID
    - SETUID
    - FOWNER
  volumes:
    - '*'
