{{- if .Values.cas }}
apiVersion: v1
kind: List
items:
{{- range .Values.cas }}
  - apiVersion: ibp.com/v1beta1
kind: IBPCA
metadata:
  name: {{ .name }}
spec:
  action:
    renew: {}
  configoverride:
    ca:
      affiliations:
      {{ toYaml .affiliations | indent 8 }} 
      registry:
        identities:
        {{ toYaml .identities | indent 8 }}
      debug: true
      signing:
        default:
          expiry: {{ .expiry }}
    tlsca:
      affiliations:
       {{ toYaml .affiliations | indent 8 }} 
      registry:
        identities:
        {{ toYaml .identities | indent 8 }}
      debug: true
      signing:
        default:
          expiry: {{ .expiry }}
  customNames:
    pvc: {}
  domain: {{ .ingress.domain }}
  images:
    caImage: {{ .ca.image.repo }}
    caTag: {{ .ca.image.tag }}
    caInitImage: {{ .init.image.repo }}
    caInitTag: {{ .init.image.tag }}
  ingress:
    class: {{ .ingress.class }}
    tlsSecretName: {{ .ingress.tlsSecretName }}
  license:
    accept: true
  replicas: {{ .replicas }}
  resources:
    ca:
    {{- toYaml .ca.resources | nindent 12 }}
    init:
      {{- toYaml .init.resources | nindent 12 }}
  service:
    type: {{ .service.type }}
  storage:
    ca:
      class: {{ .ca.pvc.class }}
      size: {{ .ca.pvc.size }}
  version: {{ .ca.version }}
{{- end }}
{{- end }}
